services:        
   complete.redis:
    container_name: complete.redis
    image: redis:latest@sha256:315270d166080f537bbdf1b489b603aaaa213cb55a544acfa51feb7481abb1c0
    restart: always
    ports:
     - "6379:6379"
    networks:
      - local-dev

networks:
  local-dev:
    
