using System.ComponentModel;

namespace Dfe.Complete.Domain.Enums;

public enum NoteTaskIdentifier
{
    [Description("handover")]
    Handover,

    // Conversion Project Task Identifiers
    [Description("stakeholder_kick_off")]
    StakeholderKickOff,
    [Description("risk_protection_arrangement")]
    RiskProtectionArrangement,
    [Description("check_accuracy_of_higher_needs")]
    CheckAccuracyOfHigherNeeds,
    [Description("complete_notification_of_change")]
    CompleteNotificationOfChange,
    [Description("conversion_grant")]
    ConversionGrant,
    [Description("sponsored_support_grant")]
    SponsoredSupportGrant,
    [Description("academy_details")]
    AcademyDetails,
    [Description("confirm_headteacher_contact")]
    ConfirmHeadteacherContact,
    [Description("confirm_chair_of_governors_contact")]
    ConfirmChairOfGovernorsContact,
    [Description("confirm_incoming_trust_ceo_contact")]
    ConfirmIncomingTrustCeoContact,
    [Description("main_contact")]
    MainContact,
    [Description("proposed_capacity_of_the_academy")]
    ProposedCapacityOfTheAcademy,
    [Description("land_questionnaire")]
    LandQuestionnaire,
    [Description("land_registry")]
    LandRegistry,
    [Description("supplemental_funding_agreement")]
    SupplementalFundingAgreement,
    [Description("church_supplemental_agreement")]
    ChurchSupplementalAgreement,
    [Description("master_funding_agreement")]
    MasterFundingAgreement,
    [Description("articles_of_association")]
    ArticlesOfAssociation,
    [Description("deed_of_variation")]
    DeedOfVariation,
    [Description("trust_modification_order")]
    TrustModificationOrder,
    [Description("direction_to_transfer")]
    DirectionToTransfer,
    [Description("one_hundred_and_twenty_five_year_lease")]
    OneHundredAndTwentyFiveYearLease,
    [Description("subleases")]
    Subleases,
    [Description("tenancy_at_will")]
    TenancyAtWill,
    [Description("commercial_transfer_agreement")]
    CommercialTransferAgreement,
    [Description("school_completed")]
    SchoolCompleted,
    [Description("conditions_met")]
    ConditionsMet,
    [Description("share_information")]
    ShareInformation,
    [Description("confirm_date_academy_opened")]
    ConfirmDateAcademyOpened,
    [Description("redact_and_send")]
    RedactAndSend,
    [Description("receive_grant_payment_certificate")]
    ReceiveGrantPaymentCertificate,

    // Transfer Project Task Identifiers
    [Description("rpa_policy")]
    RpaPolicy,
    [Description("confirm_outgoing_trust_ceo_contact")]
    ConfirmOutgoingTrustCeoContact,
    [Description("request_new_urn_and_record")]
    RequestNewUrnAndRecord,
    [Description("check_and_confirm_financial_information")]
    CheckAndConfirmFinancialInformation,
    [Description("form_m")]
    FormM,
    [Description("land_consent_letter")]
    LandConsentLetter,
    [Description("deed_of_novation_and_variation")]
    DeedOfNovationAndVariation,
    [Description("deed_of_termination_for_the_master_funding_agreement")]
    DeedOfTerminationForTheMasterFundingAgreement,
    [Description("deed_termination_church_agreement")]
    DeedTerminationChurchAgreement,
    [Description("closure_or_transfer_declaration")]
    ClosureOrTransferDeclaration,
    [Description("bank_details_changing")]
    BankDetailsChanging,
    [Description("confirm_incoming_trust_has_completed_all_actions")]
    ConfirmIncomingTrustHasCompletedAllActions,
    [Description("confirm_date_academy_transferred")]
    ConfirmDateAcademyTransferred,
    [Description("redact_and_send_documents")]
    RedactAndSendDocuments,
    [Description("declaration_of_expenditure_certificate")]
    DeclarationOfExpenditureCertificate
}