// <auto-generated />
using System;
using Dfe.Complete.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dfe.Complete.Infrastructure.Migrations
{
    [DbContext(typeof(CompleteContext))]
    [Migration("20260127140331_Baseline_FromRuby")]
    partial class Baseline_FromRuby
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("email");

                    b.Property<int?>("EstablishmentUrn")
                        .HasColumnType("int")
                        .HasColumnName("establishment_urn");

                    b.Property<Guid?>("LocalAuthorityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("local_authority_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("name");

                    b.Property<string>("OrganisationName")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("organisation_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("phone");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("contacts", "complete");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.ConversionTasksData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AcademyDetailsName")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("academy_details_name");

                    b.Property<bool?>("ArticlesOfAssociationCleared")
                        .HasColumnType("bit")
                        .HasColumnName("articles_of_association_cleared");

                    b.Property<bool?>("ArticlesOfAssociationNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("articles_of_association_not_applicable");

                    b.Property<bool?>("ArticlesOfAssociationReceived")
                        .HasColumnType("bit")
                        .HasColumnName("articles_of_association_received");

                    b.Property<bool?>("ArticlesOfAssociationSaved")
                        .HasColumnType("bit")
                        .HasColumnName("articles_of_association_saved");

                    b.Property<bool?>("ArticlesOfAssociationSent")
                        .HasColumnType("bit")
                        .HasColumnName("articles_of_association_sent");

                    b.Property<bool?>("ArticlesOfAssociationSigned")
                        .HasColumnType("bit")
                        .HasColumnName("articles_of_association_signed");

                    b.Property<bool?>("CheckAccuracyOfHigherNeedsConfirmNumber")
                        .HasColumnType("bit")
                        .HasColumnName("check_accuracy_of_higher_needs_confirm_number");

                    b.Property<bool?>("CheckAccuracyOfHigherNeedsConfirmPublishedNumber")
                        .HasColumnType("bit")
                        .HasColumnName("check_accuracy_of_higher_needs_confirm_published_number");

                    b.Property<bool?>("ChurchSupplementalAgreementCleared")
                        .HasColumnType("bit")
                        .HasColumnName("church_supplemental_agreement_cleared");

                    b.Property<bool?>("ChurchSupplementalAgreementNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("church_supplemental_agreement_not_applicable");

                    b.Property<bool?>("ChurchSupplementalAgreementReceived")
                        .HasColumnType("bit")
                        .HasColumnName("church_supplemental_agreement_received");

                    b.Property<bool?>("ChurchSupplementalAgreementSaved")
                        .HasColumnType("bit")
                        .HasColumnName("church_supplemental_agreement_saved");

                    b.Property<bool?>("ChurchSupplementalAgreementSent")
                        .HasColumnType("bit")
                        .HasColumnName("church_supplemental_agreement_sent");

                    b.Property<bool?>("ChurchSupplementalAgreementSigned")
                        .HasColumnType("bit")
                        .HasColumnName("church_supplemental_agreement_signed");

                    b.Property<bool?>("ChurchSupplementalAgreementSignedDiocese")
                        .HasColumnType("bit")
                        .HasColumnName("church_supplemental_agreement_signed_diocese");

                    b.Property<bool?>("ChurchSupplementalAgreementSignedSecretaryState")
                        .HasColumnType("bit")
                        .HasColumnName("church_supplemental_agreement_signed_secretary_state");

                    b.Property<bool?>("CommercialTransferAgreementAgreed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("commercial_transfer_agreement_agreed");

                    b.Property<bool?>("CommercialTransferAgreementQuestionsChecked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("commercial_transfer_agreement_questions_checked");

                    b.Property<bool?>("CommercialTransferAgreementQuestionsReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("commercial_transfer_agreement_questions_received");

                    b.Property<bool?>("CommercialTransferAgreementSaved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("commercial_transfer_agreement_saved");

                    b.Property<bool?>("CommercialTransferAgreementSigned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("commercial_transfer_agreement_signed");

                    b.Property<bool?>("CompleteNotificationOfChangeCheckDocument")
                        .HasColumnType("bit")
                        .HasColumnName("complete_notification_of_change_check_document");

                    b.Property<bool?>("CompleteNotificationOfChangeNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("complete_notification_of_change_not_applicable");

                    b.Property<bool?>("CompleteNotificationOfChangeSendDocument")
                        .HasColumnType("bit")
                        .HasColumnName("complete_notification_of_change_send_document");

                    b.Property<bool?>("CompleteNotificationOfChangeTellLocalAuthority")
                        .HasColumnType("bit")
                        .HasColumnName("complete_notification_of_change_tell_local_authority");

                    b.Property<DateOnly?>("ConfirmDateAcademyOpenedDateOpened")
                        .HasColumnType("date")
                        .HasColumnName("confirm_date_academy_opened_date_opened");

                    b.Property<bool?>("ConversionGrantCheckVendorAccount")
                        .HasColumnType("bit")
                        .HasColumnName("conversion_grant_check_vendor_account");

                    b.Property<bool?>("ConversionGrantNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("conversion_grant_not_applicable");

                    b.Property<bool?>("ConversionGrantPaymentForm")
                        .HasColumnType("bit")
                        .HasColumnName("conversion_grant_payment_form");

                    b.Property<bool?>("ConversionGrantSendInformation")
                        .HasColumnType("bit")
                        .HasColumnName("conversion_grant_send_information");

                    b.Property<bool?>("ConversionGrantSharePaymentDate")
                        .HasColumnType("bit")
                        .HasColumnName("conversion_grant_share_payment_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<bool?>("DeedOfVariationCleared")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_variation_cleared");

                    b.Property<bool?>("DeedOfVariationNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_variation_not_applicable");

                    b.Property<bool?>("DeedOfVariationReceived")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_variation_received");

                    b.Property<bool?>("DeedOfVariationSaved")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_variation_saved");

                    b.Property<bool?>("DeedOfVariationSent")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_variation_sent");

                    b.Property<bool?>("DeedOfVariationSigned")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_variation_signed");

                    b.Property<bool?>("DeedOfVariationSignedSecretaryState")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_variation_signed_secretary_state");

                    b.Property<bool?>("DirectionToTransferCleared")
                        .HasColumnType("bit")
                        .HasColumnName("direction_to_transfer_cleared");

                    b.Property<bool?>("DirectionToTransferNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("direction_to_transfer_not_applicable");

                    b.Property<bool?>("DirectionToTransferReceived")
                        .HasColumnType("bit")
                        .HasColumnName("direction_to_transfer_received");

                    b.Property<bool?>("DirectionToTransferSaved")
                        .HasColumnType("bit")
                        .HasColumnName("direction_to_transfer_saved");

                    b.Property<bool?>("DirectionToTransferSigned")
                        .HasColumnType("bit")
                        .HasColumnName("direction_to_transfer_signed");

                    b.Property<bool?>("HandoverMeeting")
                        .HasColumnType("bit")
                        .HasColumnName("handover_meeting");

                    b.Property<bool?>("HandoverNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("handover_not_applicable");

                    b.Property<bool?>("HandoverNotes")
                        .HasColumnType("bit")
                        .HasColumnName("handover_notes");

                    b.Property<bool?>("HandoverReview")
                        .HasColumnType("bit")
                        .HasColumnName("handover_review");

                    b.Property<bool?>("LandQuestionnaireCleared")
                        .HasColumnType("bit")
                        .HasColumnName("land_questionnaire_cleared");

                    b.Property<bool?>("LandQuestionnaireReceived")
                        .HasColumnType("bit")
                        .HasColumnName("land_questionnaire_received");

                    b.Property<bool?>("LandQuestionnaireSaved")
                        .HasColumnType("bit")
                        .HasColumnName("land_questionnaire_saved");

                    b.Property<bool?>("LandQuestionnaireSigned")
                        .HasColumnType("bit")
                        .HasColumnName("land_questionnaire_signed");

                    b.Property<bool?>("LandRegistryCleared")
                        .HasColumnType("bit")
                        .HasColumnName("land_registry_cleared");

                    b.Property<bool?>("LandRegistryReceived")
                        .HasColumnType("bit")
                        .HasColumnName("land_registry_received");

                    b.Property<bool?>("LandRegistrySaved")
                        .HasColumnType("bit")
                        .HasColumnName("land_registry_saved");

                    b.Property<bool?>("MasterFundingAgreementCleared")
                        .HasColumnType("bit")
                        .HasColumnName("master_funding_agreement_cleared");

                    b.Property<bool?>("MasterFundingAgreementNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("master_funding_agreement_not_applicable");

                    b.Property<bool?>("MasterFundingAgreementReceived")
                        .HasColumnType("bit")
                        .HasColumnName("master_funding_agreement_received");

                    b.Property<bool?>("MasterFundingAgreementSaved")
                        .HasColumnType("bit")
                        .HasColumnName("master_funding_agreement_saved");

                    b.Property<bool?>("MasterFundingAgreementSent")
                        .HasColumnType("bit")
                        .HasColumnName("master_funding_agreement_sent");

                    b.Property<bool?>("MasterFundingAgreementSigned")
                        .HasColumnType("bit")
                        .HasColumnName("master_funding_agreement_signed");

                    b.Property<bool?>("MasterFundingAgreementSignedSecretaryState")
                        .HasColumnType("bit")
                        .HasColumnName("master_funding_agreement_signed_secretary_state");

                    b.Property<bool?>("OneHundredAndTwentyFiveYearLeaseEmail")
                        .HasColumnType("bit")
                        .HasColumnName("one_hundred_and_twenty_five_year_lease_email");

                    b.Property<bool?>("OneHundredAndTwentyFiveYearLeaseNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("one_hundred_and_twenty_five_year_lease_not_applicable");

                    b.Property<bool?>("OneHundredAndTwentyFiveYearLeaseReceive")
                        .HasColumnType("bit")
                        .HasColumnName("one_hundred_and_twenty_five_year_lease_receive");

                    b.Property<bool?>("OneHundredAndTwentyFiveYearLeaseSaveLease")
                        .HasColumnType("bit")
                        .HasColumnName("one_hundred_and_twenty_five_year_lease_save_lease");

                    b.Property<bool?>("ProposedCapacityOfTheAcademyNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("proposed_capacity_of_the_academy_not_applicable");

                    b.Property<string>("ProposedCapacityOfTheAcademyReceptionToSixYears")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("proposed_capacity_of_the_academy_reception_to_six_years");

                    b.Property<string>("ProposedCapacityOfTheAcademySevenToElevenYears")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("proposed_capacity_of_the_academy_seven_to_eleven_years");

                    b.Property<string>("ProposedCapacityOfTheAcademyTwelveOrAboveYears")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("proposed_capacity_of_the_academy_twelve_or_above_years");

                    b.Property<bool?>("ReceiveGrantPaymentCertificateCheckCertificate")
                        .HasColumnType("bit")
                        .HasColumnName("receive_grant_payment_certificate_check_certificate");

                    b.Property<DateOnly?>("ReceiveGrantPaymentCertificateDateReceived")
                        .HasColumnType("date")
                        .HasColumnName("receive_grant_payment_certificate_date_received");

                    b.Property<bool?>("ReceiveGrantPaymentCertificateNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("receive_grant_payment_certificate_not_applicable");

                    b.Property<bool?>("ReceiveGrantPaymentCertificateSaveCertificate")
                        .HasColumnType("bit")
                        .HasColumnName("receive_grant_payment_certificate_save_certificate");

                    b.Property<bool?>("RedactAndSendRedact")
                        .HasColumnType("bit")
                        .HasColumnName("redact_and_send_redact");

                    b.Property<bool?>("RedactAndSendSaveRedaction")
                        .HasColumnType("bit")
                        .HasColumnName("redact_and_send_save_redaction");

                    b.Property<bool?>("RedactAndSendSendRedaction")
                        .HasColumnType("bit")
                        .HasColumnName("redact_and_send_send_redaction");

                    b.Property<bool?>("RedactAndSendSendSolicitors")
                        .HasColumnType("bit")
                        .HasColumnName("redact_and_send_send_solicitors");

                    b.Property<string>("RiskProtectionArrangementOption")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("risk_protection_arrangement_option");

                    b.Property<string>("RiskProtectionArrangementReason")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("risk_protection_arrangement_reason");

                    b.Property<bool?>("SchoolCompletedEmailed")
                        .HasColumnType("bit")
                        .HasColumnName("school_completed_emailed");

                    b.Property<bool?>("SchoolCompletedSaved")
                        .HasColumnType("bit")
                        .HasColumnName("school_completed_saved");

                    b.Property<bool?>("ShareInformationEmail")
                        .HasColumnType("bit")
                        .HasColumnName("share_information_email");

                    b.Property<bool?>("SponsoredSupportGrantInformTrust")
                        .HasColumnType("bit")
                        .HasColumnName("sponsored_support_grant_inform_trust");

                    b.Property<bool?>("SponsoredSupportGrantNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("sponsored_support_grant_not_applicable");

                    b.Property<bool?>("SponsoredSupportGrantPaymentAmount")
                        .HasColumnType("bit")
                        .HasColumnName("sponsored_support_grant_payment_amount");

                    b.Property<bool?>("SponsoredSupportGrantPaymentForm")
                        .HasColumnType("bit")
                        .HasColumnName("sponsored_support_grant_payment_form");

                    b.Property<bool?>("SponsoredSupportGrantSendInformation")
                        .HasColumnType("bit")
                        .HasColumnName("sponsored_support_grant_send_information");

                    b.Property<string>("SponsoredSupportGrantType")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("sponsored_support_grant_type");

                    b.Property<bool?>("StakeholderKickOffCheckProvisionalConversionDate")
                        .HasColumnType("bit")
                        .HasColumnName("stakeholder_kick_off_check_provisional_conversion_date");

                    b.Property<bool?>("StakeholderKickOffIntroductoryEmails")
                        .HasColumnType("bit")
                        .HasColumnName("stakeholder_kick_off_introductory_emails");

                    b.Property<bool?>("StakeholderKickOffLocalAuthorityProforma")
                        .HasColumnType("bit")
                        .HasColumnName("stakeholder_kick_off_local_authority_proforma");

                    b.Property<bool?>("StakeholderKickOffMeeting")
                        .HasColumnType("bit")
                        .HasColumnName("stakeholder_kick_off_meeting");

                    b.Property<bool?>("StakeholderKickOffSetupMeeting")
                        .HasColumnType("bit")
                        .HasColumnName("stakeholder_kick_off_setup_meeting");

                    b.Property<bool?>("SubleasesCleared")
                        .HasColumnType("bit")
                        .HasColumnName("subleases_cleared");

                    b.Property<bool?>("SubleasesEmailSigned")
                        .HasColumnType("bit")
                        .HasColumnName("subleases_email_signed");

                    b.Property<bool?>("SubleasesNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("subleases_not_applicable");

                    b.Property<bool?>("SubleasesReceiveSigned")
                        .HasColumnType("bit")
                        .HasColumnName("subleases_receive_signed");

                    b.Property<bool?>("SubleasesReceived")
                        .HasColumnType("bit")
                        .HasColumnName("subleases_received");

                    b.Property<bool?>("SubleasesSaveSigned")
                        .HasColumnType("bit")
                        .HasColumnName("subleases_save_signed");

                    b.Property<bool?>("SubleasesSaved")
                        .HasColumnType("bit")
                        .HasColumnName("subleases_saved");

                    b.Property<bool?>("SubleasesSigned")
                        .HasColumnType("bit")
                        .HasColumnName("subleases_signed");

                    b.Property<bool?>("SupplementalFundingAgreementCleared")
                        .HasColumnType("bit")
                        .HasColumnName("supplemental_funding_agreement_cleared");

                    b.Property<bool?>("SupplementalFundingAgreementReceived")
                        .HasColumnType("bit")
                        .HasColumnName("supplemental_funding_agreement_received");

                    b.Property<bool?>("SupplementalFundingAgreementSaved")
                        .HasColumnType("bit")
                        .HasColumnName("supplemental_funding_agreement_saved");

                    b.Property<bool?>("SupplementalFundingAgreementSent")
                        .HasColumnType("bit")
                        .HasColumnName("supplemental_funding_agreement_sent");

                    b.Property<bool?>("SupplementalFundingAgreementSigned")
                        .HasColumnType("bit")
                        .HasColumnName("supplemental_funding_agreement_signed");

                    b.Property<bool?>("SupplementalFundingAgreementSignedSecretaryState")
                        .HasColumnType("bit")
                        .HasColumnName("supplemental_funding_agreement_signed_secretary_state");

                    b.Property<bool?>("TenancyAtWillEmailSigned")
                        .HasColumnType("bit")
                        .HasColumnName("tenancy_at_will_email_signed");

                    b.Property<bool?>("TenancyAtWillNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("tenancy_at_will_not_applicable");

                    b.Property<bool?>("TenancyAtWillReceiveSigned")
                        .HasColumnType("bit")
                        .HasColumnName("tenancy_at_will_receive_signed");

                    b.Property<bool?>("TenancyAtWillSaveSigned")
                        .HasColumnType("bit")
                        .HasColumnName("tenancy_at_will_save_signed");

                    b.Property<bool?>("TrustModificationOrderCleared")
                        .HasColumnType("bit")
                        .HasColumnName("trust_modification_order_cleared");

                    b.Property<bool?>("TrustModificationOrderNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("trust_modification_order_not_applicable");

                    b.Property<bool?>("TrustModificationOrderReceived")
                        .HasColumnType("bit")
                        .HasColumnName("trust_modification_order_received");

                    b.Property<bool?>("TrustModificationOrderSaved")
                        .HasColumnType("bit")
                        .HasColumnName("trust_modification_order_saved");

                    b.Property<bool?>("TrustModificationOrderSentLegal")
                        .HasColumnType("bit")
                        .HasColumnName("trust_modification_order_sent_legal");

                    b.Property<bool?>("UpdateEsfaUpdate")
                        .HasColumnType("bit")
                        .HasColumnName("update_esfa_update");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("conversion_tasks_data", "complete");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.DaoRevocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfDecision")
                        .HasColumnType("date")
                        .HasColumnName("date_of_decision");

                    b.Property<string>("DecisionMakersName")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("decision_makers_name");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("dao_revocations", "complete");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.DaoRevocationReason", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("DaoRevocationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("dao_revocation_id");

                    b.Property<string>("ReasonType")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("reason_type");

                    b.HasKey("Id");

                    b.ToTable("dao_revocation_reasons", "complete");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.GiasEstablishment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AddressAdditional")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("address_additional");

                    b.Property<string>("AddressCounty")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("address_county");

                    b.Property<string>("AddressLocality")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("address_locality");

                    b.Property<string>("AddressPostcode")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("address_postcode");

                    b.Property<string>("AddressStreet")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("address_street");

                    b.Property<string>("AddressTown")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("address_town");

                    b.Property<int?>("AgeRangeLower")
                        .HasColumnType("int")
                        .HasColumnName("age_range_lower");

                    b.Property<int?>("AgeRangeUpper")
                        .HasColumnType("int")
                        .HasColumnName("age_range_upper");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DioceseCode")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("diocese_code");

                    b.Property<string>("DioceseName")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("diocese_name");

                    b.Property<string>("EstablishmentNumber")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("establishment_number");

                    b.Property<string>("LocalAuthorityCode")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("local_authority_code");

                    b.Property<string>("LocalAuthorityName")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("local_authority_name");

                    b.Property<string>("Name")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("OpenDate")
                        .HasColumnType("date")
                        .HasColumnName("open_date");

                    b.Property<string>("ParliamentaryConstituencyCode")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("parliamentary_constituency_code");

                    b.Property<string>("ParliamentaryConstituencyName")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("parliamentary_constituency_name");

                    b.Property<string>("PhaseCode")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("phase_code");

                    b.Property<string>("PhaseName")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("phase_name");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("region_code");

                    b.Property<string>("RegionName")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("region_name");

                    b.Property<string>("StatusName")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("status_name");

                    b.Property<string>("TypeCode")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("type_code");

                    b.Property<string>("TypeName")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("type_name");

                    b.Property<int?>("Ukprn")
                        .HasColumnType("int")
                        .HasColumnName("ukprn");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("url");

                    b.Property<int>("Urn")
                        .HasColumnType("int")
                        .HasColumnName("urn");

                    b.HasKey("Id");

                    b.HasAlternateKey("Urn")
                        .HasName("AK_GiasEstablishments_Urn");

                    b.HasIndex("Urn")
                        .IsUnique()
                        .HasDatabaseName("IX_GiasEstablishments_Urn");

                    b.ToTable("gias_establishments", "complete");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.GiasGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AddressAdditional")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("address_additional");

                    b.Property<string>("AddressCounty")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("address_county");

                    b.Property<string>("AddressLocality")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("address_locality");

                    b.Property<string>("AddressPostcode")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("address_postcode");

                    b.Property<string>("AddressStreet")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("address_street");

                    b.Property<string>("AddressTown")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("address_town");

                    b.Property<string>("CompaniesHouseNumber")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("companies_house_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("GroupIdentifier")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("group_identifier");

                    b.Property<string>("OriginalName")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("original_name");

                    b.Property<int?>("Ukprn")
                        .HasColumnType("int")
                        .HasColumnName("ukprn");

                    b.Property<int?>("UniqueGroupIdentifier")
                        .HasColumnType("int")
                        .HasColumnName("unique_group_identifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("gias_groups", "complete");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.KeyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChairOfGovernorsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("chair_of_governors_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("HeadteacherId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("headteacher_id");

                    b.Property<Guid?>("IncomingTrustCeoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("incoming_trust_ceo_id");

                    b.Property<Guid?>("OutgoingTrustCeoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("outgoing_trust_ceo_id");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("key_contacts", "complete");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.LocalAuthority", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("address_1");

                    b.Property<string>("Address2")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("address_2");

                    b.Property<string>("Address3")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("address_3");

                    b.Property<string>("AddressCounty")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("address_county");

                    b.Property<string>("AddressPostcode")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("address_postcode");

                    b.Property<string>("AddressTown")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("address_town");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("local_authorities", "complete");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("NotableId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("notable_id");

                    b.Property<string>("NotableType")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("notable_type");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<string>("TaskIdentifier")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("task_identifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("notes", "complete");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int?>("AcademyUrn")
                        .HasColumnType("int")
                        .HasColumnName("academy_urn");

                    b.Property<string>("AdvisoryBoardConditions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("advisory_board_conditions");

                    b.Property<DateOnly?>("AdvisoryBoardDate")
                        .HasColumnType("date")
                        .HasColumnName("advisory_board_date");

                    b.Property<bool?>("AllConditionsMet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("all_conditions_met");

                    b.Property<DateTime?>("AssignedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedToId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assigned_to_id");

                    b.Property<Guid?>("CaseworkerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("caseworker_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<bool?>("DirectiveAcademyOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("directive_academy_order");

                    b.Property<Guid?>("EstablishmentMainContactId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("establishment_main_contact_id");

                    b.Property<string>("EstablishmentSharepointLink")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("establishment_sharepoint_link");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("group_id");

                    b.Property<Guid?>("IncomingTrustMainContactId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("incoming_trust_main_contact_id");

                    b.Property<string>("IncomingTrustSharepointLink")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("incoming_trust_sharepoint_link");

                    b.Property<int?>("IncomingTrustUkprn")
                        .HasColumnType("int")
                        .HasColumnName("incoming_trust_ukprn");

                    b.Property<Guid>("LocalAuthorityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("local_authority_id");

                    b.Property<Guid?>("LocalAuthorityMainContactId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("local_authority_main_contact_id");

                    b.Property<Guid?>("MainContactId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("main_contact_id");

                    b.Property<string>("NewTrustName")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("new_trust_name");

                    b.Property<string>("NewTrustReferenceNumber")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("new_trust_reference_number");

                    b.Property<Guid?>("OutgoingTrustMainContactId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("outgoing_trust_main_contact_id");

                    b.Property<string>("OutgoingTrustSharepointLink")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("outgoing_trust_sharepoint_link");

                    b.Property<int?>("OutgoingTrustUkprn")
                        .HasColumnType("int")
                        .HasColumnName("outgoing_trust_ukprn");

                    b.Property<int?>("PrepareId")
                        .HasColumnType("int")
                        .HasColumnName("prepare_id");

                    b.Property<string>("Region")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("region");

                    b.Property<Guid>("RegionalDeliveryOfficerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("regional_delivery_officer_id");

                    b.Property<DateOnly?>("SignificantDate")
                        .HasColumnType("date")
                        .HasColumnName("significant_date");

                    b.Property<bool?>("SignificantDateProvisional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("significant_date_provisional");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("state");

                    b.Property<Guid?>("TasksDataId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tasks_data_id");

                    b.Property<string>("TasksDataType")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("tasks_data_type");

                    b.Property<string>("Team")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("team");

                    b.Property<bool?>("TwoRequiresImprovement")
                        .HasColumnType("bit")
                        .HasColumnName("two_requires_improvement");

                    b.Property<string>("Type")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("Urn")
                        .HasColumnType("int")
                        .HasColumnName("urn");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CaseworkerId");

                    b.HasIndex("LocalAuthorityId");

                    b.HasIndex("RegionalDeliveryOfficerId");

                    b.HasIndex("Urn");

                    b.ToTable("projects", "complete");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.ProjectGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("GroupIdentifier")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("group_identifier");

                    b.Property<int?>("TrustUkprn")
                        .HasColumnType("int")
                        .HasColumnName("trust_ukprn");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("project_groups", "complete");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.SignificantDateHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("PreviousDate")
                        .HasColumnType("date")
                        .HasColumnName("previous_date");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<DateOnly?>("RevisedDate")
                        .HasColumnType("date")
                        .HasColumnName("revised_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("significant_date_histories", "complete");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.SignificantDateHistoryReason", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("ReasonType")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("reason_type");

                    b.Property<Guid?>("SignificantDateHistoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("significant_date_history_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SignificantDateHistoryId");

                    b.ToTable("significant_date_history_reasons", "complete");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.TransferTasksData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool?>("ArticlesOfAssociationCleared")
                        .HasColumnType("bit")
                        .HasColumnName("articles_of_association_cleared");

                    b.Property<bool?>("ArticlesOfAssociationNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("articles_of_association_not_applicable");

                    b.Property<bool?>("ArticlesOfAssociationReceived")
                        .HasColumnType("bit")
                        .HasColumnName("articles_of_association_received");

                    b.Property<bool?>("ArticlesOfAssociationSaved")
                        .HasColumnType("bit")
                        .HasColumnName("articles_of_association_saved");

                    b.Property<bool?>("ArticlesOfAssociationSent")
                        .HasColumnType("bit")
                        .HasColumnName("articles_of_association_sent");

                    b.Property<bool?>("ArticlesOfAssociationSigned")
                        .HasColumnType("bit")
                        .HasColumnName("articles_of_association_signed");

                    b.Property<bool?>("BankDetailsChangingYesNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bank_details_changing_yes_no");

                    b.Property<string>("CheckAndConfirmFinancialInformationAcademySurplusDeficit")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("check_and_confirm_financial_information_academy_surplus_deficit");

                    b.Property<bool?>("CheckAndConfirmFinancialInformationNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("check_and_confirm_financial_information_not_applicable");

                    b.Property<string>("CheckAndConfirmFinancialInformationTrustSurplusDeficit")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("check_and_confirm_financial_information_trust_surplus_deficit");

                    b.Property<bool?>("ChurchSupplementalAgreementCleared")
                        .HasColumnType("bit")
                        .HasColumnName("church_supplemental_agreement_cleared");

                    b.Property<bool?>("ChurchSupplementalAgreementNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("church_supplemental_agreement_not_applicable");

                    b.Property<bool?>("ChurchSupplementalAgreementReceived")
                        .HasColumnType("bit")
                        .HasColumnName("church_supplemental_agreement_received");

                    b.Property<bool?>("ChurchSupplementalAgreementSavedAfterSigningBySecretaryState")
                        .HasColumnType("bit")
                        .HasColumnName("church_supplemental_agreement_saved_after_signing_by_secretary_state");

                    b.Property<bool?>("ChurchSupplementalAgreementSavedAfterSigningByTrustDiocese")
                        .HasColumnType("bit")
                        .HasColumnName("church_supplemental_agreement_saved_after_signing_by_trust_diocese");

                    b.Property<bool?>("ChurchSupplementalAgreementSignedDiocese")
                        .HasColumnType("bit")
                        .HasColumnName("church_supplemental_agreement_signed_diocese");

                    b.Property<bool?>("ChurchSupplementalAgreementSignedIncomingTrust")
                        .HasColumnType("bit")
                        .HasColumnName("church_supplemental_agreement_signed_incoming_trust");

                    b.Property<bool?>("ChurchSupplementalAgreementSignedSecretaryState")
                        .HasColumnType("bit")
                        .HasColumnName("church_supplemental_agreement_signed_secretary_state");

                    b.Property<bool?>("ClosureOrTransferDeclarationCleared")
                        .HasColumnType("bit")
                        .HasColumnName("closure_or_transfer_declaration_cleared");

                    b.Property<bool?>("ClosureOrTransferDeclarationNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("closure_or_transfer_declaration_not_applicable");

                    b.Property<bool?>("ClosureOrTransferDeclarationReceived")
                        .HasColumnType("bit")
                        .HasColumnName("closure_or_transfer_declaration_received");

                    b.Property<bool?>("ClosureOrTransferDeclarationSaved")
                        .HasColumnType("bit")
                        .HasColumnName("closure_or_transfer_declaration_saved");

                    b.Property<bool?>("ClosureOrTransferDeclarationSent")
                        .HasColumnType("bit")
                        .HasColumnName("closure_or_transfer_declaration_sent");

                    b.Property<bool?>("CommercialTransferAgreementConfirmAgreed")
                        .HasColumnType("bit")
                        .HasColumnName("commercial_transfer_agreement_confirm_agreed");

                    b.Property<bool?>("CommercialTransferAgreementConfirmSigned")
                        .HasColumnType("bit")
                        .HasColumnName("commercial_transfer_agreement_confirm_signed");

                    b.Property<bool?>("CommercialTransferAgreementQuestionsChecked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("commercial_transfer_agreement_questions_checked");

                    b.Property<bool?>("CommercialTransferAgreementQuestionsReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("commercial_transfer_agreement_questions_received");

                    b.Property<bool?>("CommercialTransferAgreementSaveConfirmationEmails")
                        .HasColumnType("bit")
                        .HasColumnName("commercial_transfer_agreement_save_confirmation_emails");

                    b.Property<bool?>("ConditionsMetBaselineSheetApproved")
                        .HasColumnType("bit")
                        .HasColumnName("conditions_met_baseline_sheet_approved");

                    b.Property<bool?>("ConditionsMetCheckAnyInformationChanged")
                        .HasColumnType("bit")
                        .HasColumnName("conditions_met_check_any_information_changed");

                    b.Property<DateOnly?>("ConfirmDateAcademyTransferredDateTransferred")
                        .HasColumnType("date")
                        .HasColumnName("confirm_date_academy_transferred_date_transferred");

                    b.Property<bool?>("ConfirmIncomingTrustHasCompletedAllActionsEmailed")
                        .HasColumnType("bit")
                        .HasColumnName("confirm_incoming_trust_has_completed_all_actions_emailed");

                    b.Property<bool?>("ConfirmIncomingTrustHasCompletedAllActionsSaved")
                        .HasColumnType("bit")
                        .HasColumnName("confirm_incoming_trust_has_completed_all_actions_saved");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<bool?>("DeclarationOfExpenditureCertificateCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("declaration_of_expenditure_certificate_correct");

                    b.Property<DateOnly?>("DeclarationOfExpenditureCertificateDateReceived")
                        .HasColumnType("date")
                        .HasColumnName("declaration_of_expenditure_certificate_date_received");

                    b.Property<bool?>("DeclarationOfExpenditureCertificateNotApplicable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("declaration_of_expenditure_certificate_not_applicable");

                    b.Property<bool?>("DeclarationOfExpenditureCertificateSaved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("declaration_of_expenditure_certificate_saved");

                    b.Property<bool?>("DeedOfNovationAndVariationCleared")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_novation_and_variation_cleared");

                    b.Property<bool?>("DeedOfNovationAndVariationReceived")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_novation_and_variation_received");

                    b.Property<bool?>("DeedOfNovationAndVariationSaveAfterSign")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_novation_and_variation_save_after_sign");

                    b.Property<bool?>("DeedOfNovationAndVariationSaved")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_novation_and_variation_saved");

                    b.Property<bool?>("DeedOfNovationAndVariationSignedIncomingTrust")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_novation_and_variation_signed_incoming_trust");

                    b.Property<bool?>("DeedOfNovationAndVariationSignedOutgoingTrust")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_novation_and_variation_signed_outgoing_trust");

                    b.Property<bool?>("DeedOfNovationAndVariationSignedSecretaryState")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_novation_and_variation_signed_secretary_state");

                    b.Property<bool?>("DeedOfTerminationForTheMasterFundingAgreementCleared")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_termination_for_the_master_funding_agreement_cleared");

                    b.Property<bool?>("DeedOfTerminationForTheMasterFundingAgreementContactFinancialReportingTeam")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_termination_for_the_master_funding_agreement_contact_financial_reporting_team");

                    b.Property<bool?>("DeedOfTerminationForTheMasterFundingAgreementNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_termination_for_the_master_funding_agreement_not_applicable");

                    b.Property<bool?>("DeedOfTerminationForTheMasterFundingAgreementReceived")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_termination_for_the_master_funding_agreement_received");

                    b.Property<bool?>("DeedOfTerminationForTheMasterFundingAgreementSavedAcademyAndOutgoingTrustSharepoint")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_termination_for_the_master_funding_agreement_saved_academy_and_outgoing_trust_sharepoint");

                    b.Property<bool?>("DeedOfTerminationForTheMasterFundingAgreementSavedInAcademySharepointFolder")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_termination_for_the_master_funding_agreement_saved_in_academy_sharepoint_folder");

                    b.Property<bool?>("DeedOfTerminationForTheMasterFundingAgreementSigned")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_termination_for_the_master_funding_agreement_signed");

                    b.Property<bool?>("DeedOfTerminationForTheMasterFundingAgreementSignedSecretaryState")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_termination_for_the_master_funding_agreement_signed_secretary_state");

                    b.Property<bool?>("DeedOfVariationCleared")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_variation_cleared");

                    b.Property<bool?>("DeedOfVariationNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_variation_not_applicable");

                    b.Property<bool?>("DeedOfVariationReceived")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_variation_received");

                    b.Property<bool?>("DeedOfVariationSaved")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_variation_saved");

                    b.Property<bool?>("DeedOfVariationSent")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_variation_sent");

                    b.Property<bool?>("DeedOfVariationSigned")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_variation_signed");

                    b.Property<bool?>("DeedOfVariationSignedSecretaryState")
                        .HasColumnType("bit")
                        .HasColumnName("deed_of_variation_signed_secretary_state");

                    b.Property<bool?>("DeedTerminationChurchAgreementCleared")
                        .HasColumnType("bit")
                        .HasColumnName("deed_termination_church_agreement_cleared");

                    b.Property<bool?>("DeedTerminationChurchAgreementNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("deed_termination_church_agreement_not_applicable");

                    b.Property<bool?>("DeedTerminationChurchAgreementReceived")
                        .HasColumnType("bit")
                        .HasColumnName("deed_termination_church_agreement_received");

                    b.Property<bool?>("DeedTerminationChurchAgreementSaved")
                        .HasColumnType("bit")
                        .HasColumnName("deed_termination_church_agreement_saved");

                    b.Property<bool?>("DeedTerminationChurchAgreementSavedAfterSigningBySecretaryState")
                        .HasColumnType("bit")
                        .HasColumnName("deed_termination_church_agreement_saved_after_signing_by_secretary_state");

                    b.Property<bool?>("DeedTerminationChurchAgreementSignedDiocese")
                        .HasColumnType("bit")
                        .HasColumnName("deed_termination_church_agreement_signed_diocese");

                    b.Property<bool?>("DeedTerminationChurchAgreementSignedOutgoingTrust")
                        .HasColumnType("bit")
                        .HasColumnName("deed_termination_church_agreement_signed_outgoing_trust");

                    b.Property<bool?>("DeedTerminationChurchAgreementSignedSecretaryState")
                        .HasColumnType("bit")
                        .HasColumnName("deed_termination_church_agreement_signed_secretary_state");

                    b.Property<bool?>("FinancialSafeguardingGovernanceIssues")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("financial_safeguarding_governance_issues");

                    b.Property<bool?>("FormMCleared")
                        .HasColumnType("bit")
                        .HasColumnName("form_m_cleared");

                    b.Property<bool?>("FormMNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("form_m_not_applicable");

                    b.Property<bool?>("FormMReceivedFormM")
                        .HasColumnType("bit")
                        .HasColumnName("form_m_received_form_m");

                    b.Property<bool?>("FormMReceivedTitlePlans")
                        .HasColumnType("bit")
                        .HasColumnName("form_m_received_title_plans");

                    b.Property<bool?>("FormMSaved")
                        .HasColumnType("bit")
                        .HasColumnName("form_m_saved");

                    b.Property<bool?>("FormMSigned")
                        .HasColumnType("bit")
                        .HasColumnName("form_m_signed");

                    b.Property<bool?>("HandoverMeeting")
                        .HasColumnType("bit")
                        .HasColumnName("handover_meeting");

                    b.Property<bool?>("HandoverNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("handover_not_applicable");

                    b.Property<bool?>("HandoverNotes")
                        .HasColumnType("bit")
                        .HasColumnName("handover_notes");

                    b.Property<bool?>("HandoverReview")
                        .HasColumnType("bit")
                        .HasColumnName("handover_review");

                    b.Property<bool?>("InadequateOfsted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("inadequate_ofsted");

                    b.Property<bool?>("LandConsentLetterDrafted")
                        .HasColumnType("bit")
                        .HasColumnName("land_consent_letter_drafted");

                    b.Property<bool?>("LandConsentLetterNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("land_consent_letter_not_applicable");

                    b.Property<bool?>("LandConsentLetterSaved")
                        .HasColumnType("bit")
                        .HasColumnName("land_consent_letter_saved");

                    b.Property<bool?>("LandConsentLetterSent")
                        .HasColumnType("bit")
                        .HasColumnName("land_consent_letter_sent");

                    b.Property<bool?>("LandConsentLetterSigned")
                        .HasColumnType("bit")
                        .HasColumnName("land_consent_letter_signed");

                    b.Property<bool?>("MasterFundingAgreementCleared")
                        .HasColumnType("bit")
                        .HasColumnName("master_funding_agreement_cleared");

                    b.Property<bool?>("MasterFundingAgreementNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("master_funding_agreement_not_applicable");

                    b.Property<bool?>("MasterFundingAgreementReceived")
                        .HasColumnType("bit")
                        .HasColumnName("master_funding_agreement_received");

                    b.Property<bool?>("MasterFundingAgreementSaved")
                        .HasColumnType("bit")
                        .HasColumnName("master_funding_agreement_saved");

                    b.Property<bool?>("MasterFundingAgreementSigned")
                        .HasColumnType("bit")
                        .HasColumnName("master_funding_agreement_signed");

                    b.Property<bool?>("MasterFundingAgreementSignedSecretaryState")
                        .HasColumnType("bit")
                        .HasColumnName("master_funding_agreement_signed_secretary_state");

                    b.Property<bool?>("OutgoingTrustToClose")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("outgoing_trust_to_close");

                    b.Property<bool?>("RedactAndSendDocumentsRedact")
                        .HasColumnType("bit")
                        .HasColumnName("redact_and_send_documents_redact");

                    b.Property<bool?>("RedactAndSendDocumentsSaved")
                        .HasColumnType("bit")
                        .HasColumnName("redact_and_send_documents_saved");

                    b.Property<bool?>("RedactAndSendDocumentsSendToEsfa")
                        .HasColumnType("bit")
                        .HasColumnName("redact_and_send_documents_send_to_esfa");

                    b.Property<bool?>("RedactAndSendDocumentsSendToFundingTeam")
                        .HasColumnType("bit")
                        .HasColumnName("redact_and_send_documents_send_to_funding_team");

                    b.Property<bool?>("RedactAndSendDocumentsSendToSolicitors")
                        .HasColumnType("bit")
                        .HasColumnName("redact_and_send_documents_send_to_solicitors");

                    b.Property<bool?>("RequestNewUrnAndRecordComplete")
                        .HasColumnType("bit")
                        .HasColumnName("request_new_urn_and_record_complete");

                    b.Property<bool?>("RequestNewUrnAndRecordGive")
                        .HasColumnType("bit")
                        .HasColumnName("request_new_urn_and_record_give");

                    b.Property<bool?>("RequestNewUrnAndRecordNotApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("request_new_urn_and_record_not_applicable");

                    b.Property<bool?>("RequestNewUrnAndRecordReceive")
                        .HasColumnType("bit")
                        .HasColumnName("request_new_urn_and_record_receive");

                    b.Property<bool?>("RpaPolicyConfirm")
                        .HasColumnType("bit")
                        .HasColumnName("rpa_policy_confirm");

                    b.Property<bool?>("SponsoredSupportGrantNotApplicable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("sponsored_support_grant_not_applicable");

                    b.Property<string>("SponsoredSupportGrantType")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("sponsored_support_grant_type");

                    b.Property<bool?>("StakeholderKickOffIntroductoryEmails")
                        .HasColumnType("bit")
                        .HasColumnName("stakeholder_kick_off_introductory_emails");

                    b.Property<bool?>("StakeholderKickOffMeeting")
                        .HasColumnType("bit")
                        .HasColumnName("stakeholder_kick_off_meeting");

                    b.Property<bool?>("StakeholderKickOffSetupMeeting")
                        .HasColumnType("bit")
                        .HasColumnName("stakeholder_kick_off_setup_meeting");

                    b.Property<bool?>("SupplementalFundingAgreementCleared")
                        .HasColumnType("bit")
                        .HasColumnName("supplemental_funding_agreement_cleared");

                    b.Property<bool?>("SupplementalFundingAgreementReceived")
                        .HasColumnType("bit")
                        .HasColumnName("supplemental_funding_agreement_received");

                    b.Property<bool?>("SupplementalFundingAgreementSaved")
                        .HasColumnType("bit")
                        .HasColumnName("supplemental_funding_agreement_saved");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("transfer_tasks_data", "complete");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ActiveDirectoryUserGroupIds")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("active_directory_user_group_ids");

                    b.Property<string>("ActiveDirectoryUserId")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("active_directory_user_id");

                    b.Property<bool>("AddNewProject")
                        .HasColumnType("bit")
                        .HasColumnName("add_new_project");

                    b.Property<bool?>("AssignToProject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("assign_to_project");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("Email")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("email");

                    b.Property<string>("EntraUserObjectId")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("entra_user_object_id");

                    b.Property<string>("FirstName")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LatestSession")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("latest_session");

                    b.Property<bool?>("ManageConversionUrns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("manage_conversion_urns");

                    b.Property<bool?>("ManageLocalAuthorities")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("manage_local_authorities");

                    b.Property<bool?>("ManageTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("manage_team");

                    b.Property<bool?>("ManageUserAccounts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("manage_user_accounts");

                    b.Property<string>("Team")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("team");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EntraUserObjectId")
                        .IsUnique()
                        .HasDatabaseName("UQ_users_entra_user_object_id")
                        .HasFilter("[entra_user_object_id] IS NOT NULL");

                    b.ToTable("users", "complete");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.Contact", b =>
                {
                    b.HasOne("Dfe.Complete.Domain.Entities.Project", "Project")
                        .WithMany("Contacts")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("fk_rails_b0485f0dbc");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.Note", b =>
                {
                    b.HasOne("Dfe.Complete.Domain.Entities.Project", "Project")
                        .WithMany("Notes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rails_99e097b079");

                    b.HasOne("Dfe.Complete.Domain.Entities.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rails_7f2323ad43");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.Project", b =>
                {
                    b.HasOne("Dfe.Complete.Domain.Entities.User", "AssignedTo")
                        .WithMany("ProjectAssignedTos")
                        .HasForeignKey("AssignedToId")
                        .HasConstraintName("fk_rails_9cf9d80ba9");

                    b.HasOne("Dfe.Complete.Domain.Entities.User", "Caseworker")
                        .WithMany("ProjectCaseworkers")
                        .HasForeignKey("CaseworkerId")
                        .HasConstraintName("fk_rails_246548228c");

                    b.HasOne("Dfe.Complete.Domain.Entities.LocalAuthority", "LocalAuthority")
                        .WithMany()
                        .HasForeignKey("LocalAuthorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rails_eddab2651f");

                    b.HasOne("Dfe.Complete.Domain.Entities.User", "RegionalDeliveryOfficer")
                        .WithMany("ProjectRegionalDeliveryOfficers")
                        .HasForeignKey("RegionalDeliveryOfficerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rails_bba1c6b145");

                    b.HasOne("Dfe.Complete.Domain.Entities.GiasEstablishment", "GiasEstablishment")
                        .WithMany()
                        .HasForeignKey("Urn")
                        .HasPrincipalKey("Urn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("Caseworker");

                    b.Navigation("GiasEstablishment");

                    b.Navigation("LocalAuthority");

                    b.Navigation("RegionalDeliveryOfficer");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.SignificantDateHistory", b =>
                {
                    b.HasOne("Dfe.Complete.Domain.Entities.Project", null)
                        .WithMany("SignificantDateHistories")
                        .HasForeignKey("ProjectId");

                    b.HasOne("Dfe.Complete.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.SignificantDateHistoryReason", b =>
                {
                    b.HasOne("Dfe.Complete.Domain.Entities.SignificantDateHistory", null)
                        .WithMany("Reasons")
                        .HasForeignKey("SignificantDateHistoryId");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.Project", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Notes");

                    b.Navigation("SignificantDateHistories");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.SignificantDateHistory", b =>
                {
                    b.Navigation("Reasons");
                });

            modelBuilder.Entity("Dfe.Complete.Domain.Entities.User", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("ProjectAssignedTos");

                    b.Navigation("ProjectCaseworkers");

                    b.Navigation("ProjectRegionalDeliveryOfficers");
                });
#pragma warning restore 612, 618
        }
    }
}
